"""add hiring rate columns

Revision ID: 03e7a317d2d7
Revises: 5176e36cd644
Create Date: 2025-11-22 21:44:20.665575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '03e7a317d2d7'
down_revision: Union[str, None] = '5176e36cd644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    jobs_columns = [c['name'] for c in inspector.get_columns('jobs')]

    if 'hiring_rate' not in jobs_columns:
        with op.batch_alter_table('jobs', schema=None) as batch_op:
            batch_op.add_column(sa.Column('hiring_rate', sa.Float(), nullable=True))
            batch_op.create_index('idx_jobs_hiring_rate', ['hiring_rate'], unique=False)

    users_columns = [c['name'] for c in inspector.get_columns('users')]
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'min_hiring_rate' not in users_columns:
            batch_op.add_column(sa.Column('min_hiring_rate', sa.Float(), nullable=True))
        
        batch_op.alter_column('receive_email',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('receive_telegram',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        
        # Check if index exists before dropping
        indexes = [i['name'] for i in inspector.get_indexes('users')]
        if 'idx_users_telegram_chat_id' in indexes:
            batch_op.drop_index(batch_op.f('idx_users_telegram_chat_id'), sqlite_where=sa.text('telegram_chat_id IS NOT NULL'))
            
        # Check if constraint exists (harder in SQLite, but create_unique_constraint usually handles it or throws specific error)
        # For simplicity, we'll assume if we dropped the index we might need the constraint.
        # But if the constraint already exists, it might fail.
        # Let's try to be safe.
        try:
            batch_op.create_unique_constraint('uq_users_telegram_chat_id', ['telegram_chat_id'])
        except ValueError:
            pass # Constraint might already exist or issue with batch mode naming

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_telegram_chat_id', type_='unique')
        batch_op.create_index(batch_op.f('idx_users_telegram_chat_id'), ['telegram_chat_id'], unique=1, sqlite_where=sa.text('telegram_chat_id IS NOT NULL'))
        batch_op.alter_column('receive_telegram',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('receive_email',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_column('min_hiring_rate')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_jobs_hiring_rate')
        batch_op.drop_column('hiring_rate')

    # ### end Alembic commands ###

