"""add hiring rate columns

Revision ID: 03e7a317d2d7
Revises: 5176e36cd644
Create Date: 2025-11-22 21:44:20.665575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e7a317d2d7'
down_revision: Union[str, None] = '5176e36cd644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hiring_rate', sa.Float(), nullable=True))
        batch_op.create_index('idx_jobs_hiring_rate', ['hiring_rate'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_hiring_rate', sa.Float(), nullable=True))
        batch_op.alter_column('receive_email',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('receive_telegram',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_index(batch_op.f('idx_users_telegram_chat_id'), sqlite_where=sa.text('telegram_chat_id IS NOT NULL'))
        batch_op.create_unique_constraint('uq_users_telegram_chat_id', ['telegram_chat_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_telegram_chat_id', type_='unique')
        batch_op.create_index(batch_op.f('idx_users_telegram_chat_id'), ['telegram_chat_id'], unique=1, sqlite_where=sa.text('telegram_chat_id IS NOT NULL'))
        batch_op.alter_column('receive_telegram',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('receive_email',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_column('min_hiring_rate')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_jobs_hiring_rate')
        batch_op.drop_column('hiring_rate')

    # ### end Alembic commands ###

